In [3]:
import mysql.connector
import pandas as pd

In [5]:
#sql connection
mydb=mysql.connector.connect(host="localhost",
user="root",
password="",
database="DS_MERGED")
my_cursor = mydb.cursor()

In [ ]:
## Customer Analysis

In [ ]:
1.Customers by Gender and Continent

In [11]:
from tabulate import tabulate
my_cursor.execute("""
    SELECT Gender, Continent, COUNT(CustomerKey) AS CustomerCount
FROM data_spark1
GROUP BY Gender, Continent
ORDER BY CustomerCount DESC;

""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("cust_by_gender_continent.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+----------+---------------+-----------------+
|    | Gender   | Continent     |   CustomerCount |
|----+----------+---------------+-----------------|
|  0 | Male     | North America |           20060 |
|  1 | Female   | North America |           19122 |
|  2 | Female   | Europe        |           10405 |
|  3 | Male     | Europe        |           10356 |
|  4 | Female   | Australia     |            1553 |
|  5 | Male     | Australia     |            1388 |
+----+----------+---------------+-----------------+

In [ ]:
2.Age Group Distribution by Country

In [13]:
from tabulate import tabulate
my_cursor.execute("""
    SELECT Country, 
       CASE 
           WHEN YEAR(CURDATE()) - YEAR(Birthday) < 25 THEN 'Under 25'
           WHEN YEAR(CURDATE()) - YEAR(Birthday) BETWEEN 25 AND 35 THEN '25-35'
           WHEN YEAR(CURDATE()) - YEAR(Birthday) BETWEEN 36 AND 50 THEN '36-50'
           ELSE 'Above 50'
       END AS AgeGroup,
       COUNT(CustomerKey) AS CustomerCount
FROM data_spark1
WHERE Birthday IS NOT NULL
GROUP BY Country, AgeGroup
ORDER BY CustomerCount DESC;

""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Age_Group_Distribution_by_Country.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+----------------+------------+-----------------+
|    | Country        | AgeGroup   |   CustomerCount |
|----+----------------+------------+-----------------|
|  0 | United States  | Above 50   |           19757 |
|  1 | United States  | 36-50      |            7378 |
|  2 | United States  | 25-35      |            5418 |
|  3 | United Kingdom | Above 50   |            4432 |
|  4 | Germany        | Above 50   |            3491 |
|  5 | Canada         | Above 50   |            3002 |
|  6 | United Kingdom | 36-50      |            1757 |
|  7 | Australia      | Above 50   |            1753 |
|  8 | United Kingdom | 25-35      |            1638 |
|  9 | Italy          | Above 50   |            1543 |
| 10 | Germany        | 36-50      |            1353 |
| 11 | Canada         | 36-50      |            1275 |
| 12 | Netherlands    | Above 50   |            1274 |
| 13 | United States  | Under 25   |            1214 |
| 14 | France         | Above 50   |            1023 |
| 15 | Germany        | 25-35      |             902 |
| 16 | Canada         | 25-35      |             870 |
| 17 | Australia      | 36-50      |             664 |
| 18 | Italy          | 36-50      |             574 |
| 19 | Netherlands    | 36-50      |             531 |
| 20 | Italy          | 25-35      |             459 |
| 21 | Australia      | 25-35      |             447 |
| 22 | Netherlands    | 25-35      |             351 |
| 23 | France         | 36-50      |             330 |
| 24 | United Kingdom | Under 25   |             313 |
| 25 | France         | 25-35      |             299 |
| 26 | Canada         | Under 25   |             268 |
| 27 | Germany        | Under 25   |             210 |
| 28 | Italy          | Under 25   |             109 |
| 29 | Netherlands    | Under 25   |              94 |
| 30 | France         | Under 25   |              78 |
| 31 | Australia      | Under 25   |              77 |
+----+----------------+------------+-----------------+

In [ ]:
3.Customer Distribution by City and Country

In [9]:
from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    City, Country,
    COUNT(CustomerKey) AS CustomerCount
FROM 
    data_spark1
GROUP BY 
    City, Country
ORDER BY 
    CustomerCount DESC;

""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Customer_Distribution_by_City_Country.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+------+--------------------------------------+----------------+-----------------+
|      | City                                 | Country        |   CustomerCount |
|------+--------------------------------------+----------------+-----------------|
|    0 | Toronto                              | Canada         |             681 |
|    1 | Los Angeles                          | United States  |             579 |
|    2 | New York                             | United States  |             569 |
|    3 | Houston                              | United States  |             438 |
|    4 | Chicago                              | United States  |             385 |
|    5 | Philadelphia                         | United States  |             382 |
|    6 | Montreal                             | Canada         |             361 |
|    7 | Dallas                               | United States  |             289 |
|    8 | Calgary                              | Canada         |             267 |
|    9 | Atlanta                              | United States  |             248 |
|   10 | Southfield                           | United States  |             239 |
|   11 | Washington                           | United States  |             239 |
|   12 | San Francisco                        | United States  |             237 |
|   13 | Seattle                              | United States  |             235 |
|   14 | Portland                             | United States  |             230 |
|   15 | Miami                                | United States  |             223 |
|   16 | Oakland                              | United States  |             206 |
|   17 | Grand Rapids                         | United States  |             203 |
|   18 | San Antonio                          | United States  |             198 |
|   19 | Jackson                              | United States  |             189 |
|   20 | Memphis                              | United States  |             189 |
|   21 | Indianapolis                         | United States  |             185 |
|   22 | Ottawa                               | Canada         |             184 |
|   23 | Vancouver                            | Canada         |             182 |
|   24 | Phoenix                              | United States  |             179 |
|   25 | Lexington                            | United States  |             176 |
|   26 | San Diego                            | United States  |             176 |
|   27 | Tampa                                | United States  |             171 |
|   28 | Sacramento                           | United States  |             165 |
|   29 | Charlotte                            | United States  |             163 |
|   30 | Denver                               | United States  |             163 |
|   31 | Birmingham                           | United States  |             162 |
|   32 | Saint Louis                          | United States  |             153 |
|   33 | Pittsburgh                           | United States  |             153 |
|   34 | Boston                               | United States  |             151 |
|   35 | Columbus                             | United States  |             147 |
|   36 | Minneapolis                          | United States  |             141 |
|   37 | Edmonton                             | Canada         |             139 |
|   38 | Nashville                            | United States  |             138 |
|   39 | Baltimore                            | United States  |             136 |
|   40 | Little Rock                          | United States  |             136 |
|   41 | Detroit                              | United States  |             135 |
|   42 | Louisville                           | United States  |             132 |
|   43 | Jacksonville                         | United States  |             132 |
|   44 | Richmond                             | United States  |             131 |
|   45 | Newark                               | United States  |             131 |
|   46 | Las Vegas                            | United States  |             131 |
|   47 | Austin                               | United States  |             130 |
|   48 | Springfield                          | United States  |             130 |
|   49 | Anaheim                              | United States  |             128 |
|   50 | Greenville                           | United States  |             127 |
|   51 | Orlando                              | United States  |             125 |
|   52 | San Jose                             | United States  |             124 |
|   53 | Irvine                               | United States  |             119 |
|   54 | Cleveland                            | United States  |             118 |
|   55 | Milwaukee                            | United States  |             116 |
|   56 | Victoria                             | Canada         |             115 |
|   57 | Quebec                               | Canada         |             113 |
|   58 | Kansas City                          | United States  |             111 |
|   59 | Camden                               | United States  |             111 |
|   60 | Fresno                               | United States  |             110 |
|   61 | Albany                               | United States  |             108 |
|   62 | Oklahoma City                        | United States  |             106 |
|   63 | Madison                              | United States  |             103 |
|   64 | Dayton                               | United States  |             101 |
|   65 | Albuquerque                          | United States  |             100 |
|   66 | München                              | Germany        |              97 |
|   67 | Columbia                             | United States  |              97 |
|   68 | Raleigh                              | United States  |              97 |
|   69 | Cambridge                            | United States  |              97 |
|   70 | Akron                                | United States  |              94 |
|   71 | Arlington                            | United States  |              93 |
|   72 | Saginaw                              | United States  |              92 |
|   73 | Tulsa                                | United States  |              92 |
|   74 | Stockton                             | United States  |              92 |
|   75 | Reno                                 | United States  |              91 |
|   76 | Salt Lake City                       | United States  |              90 |
|   77 | Englewood                            | United States  |              90 |
|   78 | Burbank                              | United States  |              87 |
|   79 | Amsterdam                            | Netherlands    |              82 |
|   80 | Montgomery                           | United States  |              82 |
|   81 | Wichita                              | United States  |              81 |
|   82 | Fort Lauderdale                      | United States  |              81 |
|   83 | West Palm Beach                      | United States  |              81 |
|   84 | El Paso                              | United States  |              80 |
|   85 | Corpus Christi                       | United States  |              80 |
|   86 | Omaha                                | United States  |              78 |
|   87 | Rochelle Park                        | United States  |              77 |
|   88 | Tucson                               | United States  |              77 |
|   89 | Worcester                            | United States  |              76 |
|   90 | Gainesville                          | United States  |              76 |
|   91 | Woburn                               | United States  |              75 |
|   92 | Fort Myers                           | United States  |              75 |
|   93 | Garden City                          | United States  |              73 |
|   94 | East Lansing                         | United States  |              73 |
|   95 | Brooklyn                             | United States  |              72 |
|   96 | Peoria                               | United States  |              72 |
|   97 | Elmsford                             | United States  |              71 |
|   98 | Fort Worth                           | United States  |              71 |
|   99 | Concord                              | United States  |              70 |
|  100 | Savannah                             | United States  |              69 |
|  101 | Toledo                               | United States  |              66 |
|  102 | Buffalo                              | United States  |              65 |
|  103 | Baton Rouge                          | United States  |              65 |
|  104 | Hartford                             | United States  |              65 |
|  105 | Manchester                           | United States  |              65 |
|  106 | Salinas                              | United States  |              65 |
|  107 | Greensboro                           | United States  |              65 |
|  108 | Eugene                               | United States  |              63 |
|  109 | Boca Raton                           | United States  |              63 |
|  110 | Syracuse                             | United States  |              62 |
|  111 | Tallahassee                          | United States  |              62 |
|  112 | Bloomfield Township                  | United States  |              61 |
|  113 | Cincinnati                           | United States  |              59 |
|  114 | Regina                               | Canada         |              58 |
|  115 | Saskatoon                            | Canada         |              58 |
|  116 | Hattiesburg                          | United States  |              58 |
|  117 | Shreveport                           | United States  |              58 |
|  118 | Florence                             | United States  |              58 |
|  119 | Wheeling                             | United States  |              58 |
|  120 | Utrecht                              | Netherlands    |              56 |
|  121 | Norcross                             | United States  |              56 |
|  122 | Mountain View                        | United States  |              56 |
|  123 | Charleston                           | United States  |              56 |
|  124 | Norfolk                              | United States  |              55 |
|  125 | Knoxville                            | United States  |              55 |
|  126 | Worthington                          | United States  |              55 |
|  127 | New Brunswick                        | United States  |              55 |
|  128 | Den Haag                             | Netherlands    |              53 |
|  129 | Westland                             | United States  |              53 |
|  130 | New Orleans                          | United States  |              52 |
|  131 | Harrisburg                           | United States  |              52 |
|  132 | Nürnberg                             | Germany        |              51 |
|  133 | Wayne                                | United States  |              51 |
|  134 | Lafayette                            | United States  |              51 |
|  135 | Bloomington                          | United States  |              51 |
|  136 | Winnipeg                             | Canada         |              50 |
|  137 | London                               | Canada         |              50 |
|  138 | Harlingen                            | United States  |              50 |
|  139 | Paris                                | France         |              49 |
|  140 | Fort Smith                           | United States  |              49 |
|  141 | Golden Valley                        | United States  |              49 |
|  142 | Mansfield                            | United States  |              49 |
|  143 | Westerville                          | United States  |              49 |
|  144 | Lincoln                              | United States  |              49 |
|  145 | Rochester                            | United States  |              48 |
|  146 | Boise                                | United States  |              48 |
|  147 | Ocala                                | United States  |              47 |
|  148 | Crafton                              | United States  |              47 |
|  149 | Hamilton                             | Canada         |              46 |
|  150 | Oshawa                               | Canada         |              46 |
|  151 | Livonia                              | United States  |              46 |
|  152 | Bakersfield                          | United States  |              46 |
|  153 | Bridgeview                           | United States  |              46 |
|  154 | Providence                           | United States  |              45 |
|  155 | New Haven                            | United States  |              45 |
|  156 | Hickory Hills                        | United States  |              45 |
|  157 | Youngstown                           | United States  |              45 |
|  158 | Huntsville                           | United States  |              44 |
|  159 | Silver Spring                        | United States  |              44 |
|  160 | Duluth                               | United States  |              44 |
|  161 | Portsmouth                           | United States  |              44 |
|  162 | Dresden                              | Germany        |              43 |
|  163 | Apeldoorn                            | Netherlands    |              43 |
|  164 | Winston Salem                        | United States  |              43 |
|  165 | Lansing                              | United States  |              43 |
|  166 | Jersey City                          | United States  |              43 |
|  167 | Marquette                            | United States  |              43 |
|  168 | Westminster                          | United States  |              43 |
|  169 | Everett                              | United States  |              43 |
|  170 | Trois Rivieres                       | Canada         |              42 |
|  171 | Kitchener                            | Canada         |              42 |
|  172 | Windsor                              | Canada         |              42 |
|  173 | Zwolle                               | Netherlands    |              42 |
|  174 | Eindhoven                            | Netherlands    |              42 |
|  175 | Bloomsburg                           | United States  |              42 |
|  176 | Santa Clara                          | United States  |              42 |
|  177 | Chattanooga                          | United States  |              42 |
|  178 | Arlington Heights                    | United States  |              42 |
|  179 | Brentwood                            | United States  |              42 |
|  180 | Rupert                               | United States  |              42 |
|  181 | New Westminster                      | Canada         |              41 |
|  182 | Honolulu                             | United States  |              41 |
|  183 | Reston                               | United States  |              41 |
|  184 | Lubbock                              | United States  |              41 |
|  185 | Waukesha                             | United States  |              41 |
|  186 | Eagleville                           | United States  |              40 |
|  187 | Wooster                              | United States  |              40 |
|  188 | Warrensville Heights                 | United States  |              40 |
|  189 | Bedford                              | United States  |              40 |
|  190 | Norwalk                              | United States  |              40 |
|  191 | Stlouis                              | United States  |              40 |
|  192 | Frisco                               | United States  |              40 |
|  193 | Pensacola                            | United States  |              39 |
|  194 | Plymouth                             | United States  |              39 |
|  195 | Cedar Rapids                         | United States  |              39 |
|  196 | Spokane                              | United States  |              39 |
|  197 | Des Moines                           | United States  |              39 |
|  198 | Chemnitz                             | Germany        |              38 |
|  199 | Midland                              | United States  |              38 |
|  200 | Beltsville                           | United States  |              38 |
|  201 | West Nyack                           | United States  |              38 |
|  202 | Piscataway                           | United States  |              38 |
|  203 | Poughkeepsie                         | United States  |              38 |
|  204 | Rotterdam                            | Netherlands    |              37 |
|  205 | Roanoke                              | United States  |              37 |
|  206 | Bridgeport                           | United States  |              37 |
|  207 | Decatur                              | United States  |              37 |
|  208 | Franklin                             | United States  |              37 |
|  209 | Red Bank                             | United States  |              37 |
|  210 | Warren                               | United States  |              37 |
|  211 | Burlington                           | Canada         |              36 |
|  212 | Red Deer                             | Canada         |              36 |
|  213 | Galdo Degli Alburni                  | Italy          |              36 |
|  214 | Ontario                              | United States  |              36 |
|  215 | Sugar Land                           | United States  |              36 |
|  216 | Anchorage                            | United States  |              36 |
|  217 | Fayetteville                         | United States  |              36 |
|  218 | Kelowna                              | Canada         |              35 |
|  219 | Dublin                               | United States  |              35 |
|  220 | Middletown                           | United States  |              35 |
|  221 | Beaverton                            | United States  |              35 |
|  222 | Deerfield Beach                      | United States  |              35 |
|  223 | El Monte                             | United States  |              35 |
|  224 | Bensenville                          | United States  |              35 |
|  225 | Chicoutimi                           | Canada         |              34 |
|  226 | Kiel                                 | Germany        |              34 |
|  227 | Bridgeville                          | United States  |              34 |
|  228 | Alexandria                           | United States  |              34 |
|  229 | Mobile                               | United States  |              34 |
|  230 | Gardena                              | United States  |              34 |
|  231 | Owensboro                            | United States  |              34 |
|  232 | Green Bay                            | United States  |              34 |
|  233 | Riverside                            | United States  |              34 |
|  234 | Queens                               | United States  |              34 |
|  235 | Norderstedt                          | Germany        |              33 |
|  236 | Champaign                            | United States  |              33 |

In [ ]:
3.1 sales performance across different product categories and subcategories

In [11]:
from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    Category, 
    Subcategory, 
    SUM(Quantity * `Unit Price USD`) AS Total_Sales
FROM 
    data_spark1
GROUP BY 
    Category, Subcategory
ORDER BY 
    Total_Sales DESC;


""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("sales performance across different product categories and subcategories.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+-------------------------------+----------------------------------+------------------+
|    | Category                      | Subcategory                      |      Total_Sales |
|----+-------------------------------+----------------------------------+------------------|
|  0 | Computers                     | Desktops                         |      9.90636e+06 |
|  1 | TV and Video                  | Televisions                      |      4.30872e+06 |
|  2 | Computers                     | Projectors & Screens             |      3.76752e+06 |
|  3 | Home Appliances               | Water Heaters                    |      3.54782e+06 |
|  4 | Cameras and camcorders        | Camcorders                       |      3.35799e+06 |
|  5 | Computers                     | Laptops                          |      3.16478e+06 |
|  6 | Music, Movies and Audio Books | Movie DVD                        |      3.13101e+06 |
|  7 | Cell phones                   | Touch Screen Phones              |      3.08346e+06 |
|  8 | Cell phones                   | Smart phones & PDAs              |      2.80566e+06 |
|  9 | Home Appliances               | Refrigerators                    |      2.15266e+06 |
| 10 | Home Appliances               | Washers & Dryers                 |      2.11985e+06 |
| 11 | Cameras and camcorders        | Digital SLR Cameras              |      1.89464e+06 |
| 12 | Computers                     | Monitors                         |      1.51812e+06 |
| 13 | Audio                         | Bluetooth Headphones             |      1.3804e+06  |
| 14 | Audio                         | Recording Pen                    |      1.31042e+06 |
| 15 | Home Appliances               | Coffee Machines                  |      1.16774e+06 |
| 16 | Home Appliances               | Microwaves                       |      1.10148e+06 |
| 17 | Cameras and camcorders        | Digital Cameras                  | 885680           |
| 18 | Computers                     | Printers, Scanners & Fax         | 733478           |
| 19 | TV and Video                  | Home Theater System              | 718397           |
| 20 | Games and Toys                | Download Games                   | 632878           |
| 21 | TV and Video                  | Car Video                        | 587888           |
| 22 | Audio                         | MP4&MP3                          | 478802           |
| 23 | Cameras and camcorders        | Cameras & Camcorders Accessories | 381857           |
| 24 | Home Appliances               | Air Conditioners                 | 333585           |
| 25 | TV and Video                  | VCD & DVD                        | 313978           |
| 26 | Home Appliances               | Lamps                            | 272966           |
| 27 | Computers                     | Computers Accessories            | 211346           |
| 28 | Cell phones                   | Home & Office Phones             | 165724           |
| 29 | Cell phones                   | Cell phones Accessories          | 128948           |
| 30 | Home Appliances               | Fans                             |  99370.5         |
| 31 | Games and Toys                | Boxed Games                      |  91951.1         |
+----+-------------------------------+----------------------------------+------------------+

In [ ]:
SELECT 
    Category, 
    Subcategory, 
    SUM(Quantity * Unit_Price_USD) AS Total_Sales
FROM 
    data_spark1
GROUP BY 
    Category, Subcategory
ORDER BY 
    Total_Sales DESC;

In [ ]:
Sales Analysis

In [ ]:
4.Overall Sales Performance Over Time

In [25]:
from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    DATE_FORMAT(`Order Date`, '%Y-%m') AS month,
    SUM(`Quantity` * `Unit Price USD`) AS total_sales
FROM 
    data_spark1
GROUP BY 
    month
ORDER BY 
    month;

""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Overall_Sales_Performance_Over_Time.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+---------+------------------+
|    | month   |      total_sales |
|----+---------+------------------|
|  0 | 2016-01 | 649919           |
|  1 | 2016-02 | 891098           |
|  2 | 2016-03 | 338407           |
|  3 | 2016-04 | 110592           |
|  4 | 2016-05 | 595986           |
|  5 | 2016-06 | 518585           |
|  6 | 2016-07 | 454960           |
|  7 | 2016-08 | 547513           |
|  8 | 2016-09 | 567421           |
|  9 | 2016-10 | 623960           |
| 10 | 2016-11 | 649949           |
| 11 | 2016-12 | 998403           |
| 12 | 2017-01 | 670115           |
| 13 | 2017-02 | 750526           |
| 14 | 2017-03 | 331249           |
| 15 | 2017-04 |  58580.1         |
| 16 | 2017-05 | 616259           |
| 17 | 2017-06 | 631731           |
| 18 | 2017-07 | 511787           |
| 19 | 2017-08 | 593379           |
| 20 | 2017-09 | 686375           |
| 21 | 2017-10 | 628521           |
| 22 | 2017-11 | 655723           |
| 23 | 2017-12 |      1.28718e+06 |
| 24 | 2018-01 | 917075           |
| 25 | 2018-02 |      1.34434e+06 |
| 26 | 2018-03 | 434951           |
| 27 | 2018-04 |  70627.5         |
| 28 | 2018-05 |      1.07327e+06 |
| 29 | 2018-06 | 973975           |
| 30 | 2018-07 | 964149           |
| 31 | 2018-08 |      1.02685e+06 |
| 32 | 2018-09 |      1.18177e+06 |
| 33 | 2018-10 |      1.24173e+06 |
| 34 | 2018-11 |      1.47803e+06 |
| 35 | 2018-12 |      2.08221e+06 |
| 36 | 2019-01 |      1.9409e+06  |
| 37 | 2019-02 |      2.10286e+06 |
| 38 | 2019-03 | 845925           |
| 39 | 2019-04 | 149893           |
| 40 | 2019-05 |      1.59445e+06 |
| 41 | 2019-06 |      1.40486e+06 |
| 42 | 2019-07 |      1.40871e+06 |
| 43 | 2019-08 |      1.50078e+06 |
| 44 | 2019-09 |      1.54787e+06 |
| 45 | 2019-10 |      1.57517e+06 |
| 46 | 2019-11 |      1.71566e+06 |
| 47 | 2019-12 |      2.4773e+06  |
| 48 | 2020-01 |      2.06895e+06 |
| 49 | 2020-02 |      2.22738e+06 |
| 50 | 2020-03 | 674991           |
| 51 | 2020-04 | 217642           |
| 52 | 2020-05 | 878027           |
| 53 | 2020-06 | 763883           |
| 54 | 2020-07 | 512805           |
| 55 | 2020-08 | 416647           |
| 56 | 2020-09 | 380432           |
| 57 | 2020-10 | 245648           |
| 58 | 2020-11 | 256701           |
| 59 | 2020-12 | 651526           |
| 60 | 2021-01 | 513022           |
| 61 | 2021-02 | 526267           |
+----+---------+------------------+

In [ ]:
5.Sales by Product and Currency

In [77]:
from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    Productkey,`Currency code`,
    SUM(Quantity) AS Quantity_Sold,
    SUM(Quantity * `Unit Price USD`) AS Revenue
FROM 
    data_spark1
GROUP BY 
    Productkey,`Currency code`
ORDER BY 
    Revenue DESC limitc 100;

""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Sales_by_Product_and_Currency.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+--------------+-----------------+-----------------+-----------+
|    |   Productkey | Currency code   |   Quantity_Sold |   Revenue |
|----+--------------+-----------------+-----------------+-----------|
|  0 |          444 | USD             |             329 |  302351   |
|  1 |          433 | USD             |             272 |  263568   |
|  2 |          422 | USD             |             267 |  258723   |
|  3 |          455 | USD             |             259 |  238021   |
|  4 |          428 | USD             |             240 |  232560   |
|  5 |          416 | USD             |             237 |  229653   |
|  6 |          438 | USD             |             234 |  215046   |
|  7 |          147 | USD             |              70 |  202999   |
|  8 |          146 | USD             |              69 |  200099   |
|  9 |          450 | USD             |             210 |  192990   |
| 10 |          434 | USD             |             310 |  185690   |
| 11 |          145 | EUR             |              61 |  176899   |
| 12 |          148 | USD             |              58 |  168199   |
| 13 |          417 | USD             |             244 |  146156   |
| 14 |          451 | USD             |             256 |  143104   |
| 15 |          423 | USD             |             234 |  140166   |
| 16 |          456 | USD             |             239 |  133601   |
| 17 |         1927 | USD             |              41 |  131200   |
| 18 |          432 | USD             |             254 |  126975   |
| 19 |          439 | USD             |             222 |  124098   |
| 20 |         2085 | USD             |              84 |  123900   |
| 21 |          420 | USD             |             247 |  123475   |
| 22 |          161 | USD             |              77 |  122599   |
| 23 |          421 | USD             |             259 |  121471   |
| 24 |          429 | USD             |             197 |  118180   |
| 25 |          147 | EUR             |              40 |  116000   |
| 26 |          427 | USD             |             246 |  115374   |
| 27 |          600 | USD             |              44 |  109956   |
| 28 |         2110 | USD             |              74 |  109150   |
| 29 |          425 | USD             |             294 |  108486   |
| 30 |          437 | USD             |             216 |  107978   |
| 31 |          419 | USD             |             291 |  107379   |
| 32 |          145 | USD             |              37 |  107300   |
| 33 |          426 | USD             |             214 |  106979   |
| 34 |          164 | USD             |              67 |  106677   |
| 35 |          444 | EUR             |             116 |  106604   |
| 36 |          445 | USD             |             185 |  103415   |
| 37 |          416 | EUR             |             106 |  102714   |
| 38 |          539 | USD             |              44 |  100980   |
| 39 |          576 | USD             |              40 |   99960   |
| 40 |          540 | USD             |              40 |   99960   |
| 41 |          450 | EUR             |             108 |   99252   |
| 42 |          634 | USD             |              39 |   97461   |
| 43 |         2095 | USD             |              66 |   97350   |
| 44 |         2100 | USD             |              66 |   97350   |
| 45 |         1897 | USD             |              30 |   95999.7 |
| 46 |          428 | EUR             |              98 |   94962   |
| 47 |          455 | EUR             |             103 |   94657   |
| 48 |          436 | USD             |             252 |   92988   |
| 49 |         2091 | USD             |             102 |   89505   |
| 50 |          622 | USD             |              39 |   89505   |
| 51 |         2086 | USD             |             102 |   89505   |
| 52 |          599 | USD             |              39 |   89505   |
| 53 |          449 | USD             |             256 |   89344   |
| 54 |          422 | EUR             |              92 |   89148   |
| 55 |         1206 | USD             |              57 |   88920   |
| 56 |         2106 | USD             |             101 |   88627.5 |
| 57 |          623 | USD             |              35 |   87465   |
| 58 |          443 | USD             |             247 |   86203   |
| 59 |          423 | EUR             |             142 |   85058   |
| 60 |          157 | USD             |              77 |   84699.2 |
| 61 |         2096 | USD             |              96 |   84240   |
| 62 |          163 | USD             |              52 |   82794.4 |
| 63 |          160 | USD             |              74 |   81399.3 |
| 64 |          460 | USD             |             261 |   78273.9 |
| 65 |         2105 | USD             |              53 |   78175   |
| 66 |          162 | USD             |              49 |   78017.8 |
| 67 |         1951 | USD             |              24 |   76799.8 |
| 68 |          418 | USD             |             283 |   76395.9 |
| 69 |          424 | USD             |             282 |   76125.9 |
| 70 |          587 | USD             |              33 |   75735   |
| 71 |         2095 | EUR             |              51 |   75225   |
| 72 |         2092 | USD             |              95 |   75145   |
| 73 |          612 | USD             |              30 |   74970   |
| 74 |          448 | USD             |             276 |   74492.4 |
| 75 |          551 | USD             |              32 |   73440   |
| 76 |          431 | USD             |             199 |   73431   |
| 77 |          148 | EUR             |              25 |   72499.7 |
| 78 |          438 | EUR             |              78 |   71682   |
| 79 |          416 | GBP             |              73 |   70737   |
| 80 |          428 | GBP             |              73 |   70737   |
| 81 |         1909 | USD             |              22 |   70399.8 |
| 82 |          442 | USD             |             260 |   70174   |
| 83 |         2105 | EUR             |              47 |   69325   |
| 84 |         1443 | USD             |             116 |   68324   |
| 85 |         2090 | USD             |              46 |   67850   |
| 86 |          146 | EUR             |              23 |   66699.8 |
| 87 |          452 | USD             |             303 |   66644.8 |
| 88 |         1426 | USD             |             113 |   66557   |
| 89 |         2102 | USD             |              84 |   66444   |
| 90 |          450 | GBP             |              72 |   66168   |
| 91 |          158 | USD             |              60 |   65999.4 |
| 92 |          433 | EUR             |              68 |   65892   |
| 93 |          152 | USD             |              55 |   65173.3 |
| 94 |         1409 | USD             |             109 |   64201   |
| 95 |          151 | USD             |              54 |   63988.4 |
| 96 |          458 | USD             |             278 |   63912.2 |
| 97 |         1650 | USD             |             219 |   63507.8 |
| 98 |          453 | USD             |             276 |   63452.4 |
| 99 |          454 | USD             |             234 |   63156.6 |
+----+--------------+-----------------+-----------------+-----------+

In [ ]:
Product Analysis

In [ ]:
6.Top Performing Products by Quantity Sold

In [75]:
from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    `Product Name`,
    SUM(`Quantity`) AS total_quantity_sold,
    SUM(`Quantity` * `Unit Price USD`) AS total_revenue
FROM 
    data_spark1
GROUP BY 
    `Product Name`
ORDER BY 
    total_quantity_sold DESC limit 100;


""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Top_Performing_Products_by_Quantity_Sold.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+-----------------------------------------------------+-----------------------+-----------------+
|    | Product Name                                        |   total_quantity_sold |   total_revenue |
|----+-----------------------------------------------------+-----------------------+-----------------|
|  0 | WWI Desktop PC2.33 X2330 Black                      |                   550 |       505450    |
|  1 | WWI Desktop PC1.80 E1800 White                      |                   538 |       123686    |
|  2 | Adventure Works Desktop PC1.60 ED160 Black          |                   521 |       140644    |
|  3 | Adventure Works Desktop PC2.30 MD230 White          |                   521 |       312079    |
|  4 | Adventure Works Desktop PC1.80 ED180 Black          |                   520 |       191880    |
|  5 | Adventure Works Desktop PC2.30 MD230 Black          |                   514 |       307886    |
|  6 | WWI Desktop PC1.60 E1600 Black                      |                   509 |       111955    |
|  7 | WWI Desktop PC1.60 E1600 Silver                     |                   507 |       111515    |
|  8 | WWI Desktop PC1.80 E1801 Black                      |                   505 |       136299    |
|  9 | Adventure Works Desktop PC1.60 ED160 White          |                   505 |       136325    |
| 10 | WWI Desktop PC1.60 E1600 Red                        |                   505 |       111075    |
| 11 | Adventure Works Desktop PC1.80 ED180 Silver         |                   493 |       181917    |
| 12 | Adventure Works Desktop PC1.80 ED180 White          |                   490 |       180810    |
| 13 | Adventure Works Desktop PC2.33 XD233 Silver         |                   481 |       466089    |
| 14 | Adventure Works Desktop PC2.30 MD230 Silver         |                   480 |       287520    |
| 15 | WWI Desktop PC1.80 E1800 Silver                     |                   480 |       110352    |
| 16 | Adventure Works Desktop PC2.33 XD233 Brown          |                   479 |       464151    |
| 17 | Adventure Works Desktop PC1.80 ED182 Silver         |                   477 |       238452    |
| 18 | Adventure Works Desktop PC3.0 MS300 Black           |                   476 |       223244    |
| 19 | WWI Desktop PC1.80 E1802 White                      |                   464 |       139154    |
| 20 | Adventure Works Desktop PC3.0 MS300 Silver          |                   464 |       217616    |
| 21 | WWI Desktop PC2.33 X2330 White                      |                   462 |       424578    |
| 22 | Adventure Works Desktop PC2.33 XD233 Black          |                   462 |       447678    |
| 23 | WWI Desktop PC2.33 X2330 Brown                      |                   460 |       422740    |
| 24 | WWI Desktop PC2.30 M2300 Brown                      |                   458 |       256022    |
| 25 | WWI Desktop PC2.30 M2300 Silver                     |                   456 |       254904    |
| 26 | Adventure Works Desktop PC1.60 ED160 Brown          |                   455 |       122827    |
| 27 | WWI Desktop PC3.0 M0300 Black                       |                   453 |       158097    |
| 28 | Adventure Works Desktop PC2.33 XD233 White          |                   451 |       437019    |
| 29 | WWI Desktop PC2.30 M2300 White                      |                   448 |       250432    |
| 30 | Adventure Works Desktop PC1.80 ED182 Brown          |                   439 |       219456    |
| 31 | WWI 1GB Digital Voice Recorder Pen E100 Black       |                   431 |        67236    |
| 32 | Adventure Works Desktop PC1.60 ED160 Silver         |                   430 |       116079    |
| 33 | WWI Desktop PC1.80 E1801 Brown                      |                   428 |       115517    |
| 34 | WWI Desktop PC1.60 E1600 White                      |                   424 |        93258.8  |
| 35 | WWI Desktop PC3.0 M0300 Silver                      |                   421 |       146929    |
| 36 | WWI Desktop PC1.80 E1801 Silver                     |                   415 |       112008    |
| 37 | WWI Desktop PC1.80 E1801 White                      |                   409 |       110389    |
| 38 | Adventure Works Desktop PC2.30 MD230 Brown          |                   405 |       242960    |
| 39 | SV DVD Player M120 White                            |                   404 |        23832    |
| 40 | SV DVD 12-Inch Player Portable M400 White           |                   401 |        72176    |
| 41 | Adventure Works Desktop PC1.80 ED182 White          |                   400 |       199960    |
| 42 | WWI Desktop PC2.33 X2330 Silver                     |                   392 |       360248    |
| 43 | Adventure Works Desktop PC1.80 ED182 Black          |                   392 |       195961    |
| 44 | SV DVD 14-Inch Player Portable L100 Silver          |                   391 |       101656    |
| 45 | WWI 1GB Digital Voice Recorder Pen E100 Red         |                   388 |        60528    |
| 46 | WWI Desktop PC2.30 M2300 Black                      |                   386 |       215774    |
| 47 | SV DVD External DVD Burner M200 Black               |                   384 |        22225.9  |
| 48 | Contoso DVD 55DVD Storage Binder M56 Silver         |                   380 |         4810.8  |
| 49 | WWI Desktop PC1.80 E1800 Black                      |                   377 |        86672.3  |
| 50 | Contoso DVD 7-Inch Player Portable E200 Black       |                   376 |        41356.2  |
| 51 | Adventure Works Desktop PC1.80 ED180 Brown          |                   376 |       138744    |
| 52 | Contoso DVD Player M100 Black                       |                   376 |        21428.2  |
| 53 | MGS Hand Games men M300 Red                         |                   376 |         2590.64 |
| 54 | SV DVD Recorder L210 Silver                         |                   372 |        81468    |
| 55 | Contoso DVD 7-Inch Player Portable E200 Silver      |                   372 |        40916.3  |
| 56 | Contoso DVD Recorder L230 Grey                      |                   371 |        81249    |
| 57 | WWI 4GB Video Recording Pen X200 Yellow             |                   370 |       109520    |
| 58 | Contoso DVD 12-Inch Player Portable M400 Silver     |                   370 |        66596.3  |
| 59 | SV DVD 55DVD Storage Binder M56 Black               |                   370 |         4684.2  |
| 60 | SV DVD 55DVD Storage Binder M56 Red                 |                   368 |         4658.88 |
| 61 | WWI 4GB Video Recording Pen X200 Black              |                   366 |       108336    |
| 62 | SV DVD 7-Inch Player Portable E200 White            |                   365 |        40146.3  |
| 63 | Contoso DVD Player M110 Silver                      |                   360 |        20876.4  |
| 64 | Contoso DVD External DVD Burner M200 Grey           |                   360 |        20836.8  |
| 65 | WWI Wireless Bluetooth Stereo Headphones M270 Black |                   359 |        41285    |
| 66 | WWI 1GB Digital Voice Recorder Pen E100 White       |                   357 |        55692    |
| 67 | Contoso DVD 55DVD Storage Binder M56 Red            |                   357 |         4519.62 |
| 68 | Contoso DVD 38 DVD Storage Binder E25 Black         |                   356 |         3556.44 |
| 69 | SV DVD Recorder L240 Gold                           |                   355 |        77745    |
| 70 | WWI 1GB Pulse Smart pen E50 Silver                  |                   355 |        53232.2  |
| 71 | Contoso DVD 9-Inch Player Portable M300 Black       |                   355 |        56796.5  |
| 72 | WWI 2GB Spy Video Recorder Pen M300 Purple          |                   353 |        63893    |
| 73 | Contoso DVD 48 DVD Storage Binder M50 Red           |                   352 |         6332.48 |
| 74 | Contoso DVD 14-Inch Player Portable L100 Black      |                   349 |        90736.5  |
| 75 | WWI Desktop PC1.80 E1800 Brown                      |                   348 |        80005.2  |
| 76 | SV DVD 38 DVD Storage Binder E25 Red                |                   348 |         3476.52 |
| 77 | Contoso DVD 48 DVD Storage Binder M50 Silver        |                   348 |         6260.52 |
| 78 | Contoso DVD Player M130 Grey                        |                   346 |        20756.5  |
| 79 | Contoso DVD Movies E100 Yellow                      |                   345 |         4481.55 |
| 80 | WWI 2GB Pulse Smart pen M100 Blue                   |                   345 |        68982.7  |
| 81 | Contoso DVD External DVD Burner M200 Silver         |                   342 |        19795    |
| 82 | SV DVD 15-Inch Player Portable L200 Black           |                   340 |        98596.6  |
| 83 | WWI 2GB Spy Video Recorder Pen M300 Black           |                   340 |        61540    |
| 84 | SV DVD 14-Inch Player Portable L100 White           |                   340 |        88396.6  |
| 85 | SV DVD 12-Inch Player Portable M400 Black           |                   336 |        60476.6  |
| 86 | Contoso DVD 9-Inch Player Portable M300 Silver      |                   336 |        53756.6  |
| 87 | SV DVD Player M100 Black                            |                   334 |        19034.7  |
| 88 | Contoso DVD 9-Inch Player Portable M300 White       |                   333 |        53276.7  |
| 89 | Contoso DVD 15-Inch Player Portable L200 Black      |                   331 |        95986.7  |
| 90 | SV DVD 7-Inch Player Portable E200 Silver           |                   329 |        36186.7  |
| 91 | Contoso DVD 12-Inch Player Portable M400 Black      |                   329 |        59216.7  |
| 92 | Contoso DVD 15-Inch Player Portable L200 White      |                   329 |        95406.7  |
| 93 | SV DVD 58 DVD Storage Binder M55 Red                |                   328 |         4555.92 |
| 94 | WWI 4GB Video Recording Pen X200 Red                |                   328 |        97088    |
| 95 | SV DVD 55DVD Storage Binder M56 Silver              |                   326 |         4127.16 |
| 96 | SV DVD 58 DVD Storage Binder M55 Black              |                   325 |         4514.25 |
| 97 | Contoso DVD 15-Inch Player Portable L200 Silver     |                   325 |        94246.7  |
| 98 | WWI 2GB Spy Video Recorder Pen M300 Silver          |                   324 |        58644    |
| 99 | Contoso DVD 55DVD Storage Binder M56 Black          |                   323 |         4089.18 |
+----+-----------------------------------------------------+-----------------------+-----------------+

In [ ]:
6.1 Least Performing Products by Quantity Sold

In [73]:
from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    `Product Name`,
    SUM(`Quantity`) AS total_quantity_sold,
    SUM(`Quantity` * `Unit Price USD`) AS total_revenue
FROM 
    data_spark1
GROUP BY 
    `Product Name`
ORDER BY 
    total_quantity_sold ASC limit 100;


""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Least_Performing_Products_by_Quantity_Sold.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+-------------------------------------------------------------+-----------------------+-----------------+
|    | Product Name                                                |   total_quantity_sold |   total_revenue |
|----+-------------------------------------------------------------+-----------------------+-----------------|
|  0 | Proseware Wall Lamp E0215 Blue                              |                     1 |          119.99 |
|  1 | Adventure Works Chandelier M8150 Silver                     |                     1 |          268.5  |
|  2 | Adventure Works Desk Lamp E1300 Black                       |                     1 |           79.95 |
|  3 | WWI Floor Lamp M215 Grey                                    |                     1 |          339    |
|  4 | WWI Wall Lamp E315 White                                    |                     1 |          101.99 |
|  5 | Proseware Chandelier M0815 Black                            |                     1 |          268.5  |
|  6 | WWI Floor Lamp X115 Blue                                    |                     1 |          635.99 |
|  7 | Adventure Works Chandelier M8150 Black                      |                     1 |          268.5  |
|  8 | Litware 16" White Oscillating Stand Fan E701 White          |                     1 |           29.09 |
|  9 | Proseware Floor Lamp X0115 Blue                             |                     1 |          635.99 |
| 10 | Litware Home Theater System 5.1 Channel M511 Black          |                     2 |         1398    |
| 11 | Contoso Air conditioner 25000BTU L1672 Blue                 |                     2 |         1271.98 |
| 12 | WWI Chandelier M615 Black                                   |                     2 |          459.98 |
| 13 | WWI Chandelier M815 Black                                   |                     2 |          537    |
| 14 | Adventure Works Floor Lamp X1150 Blue                       |                     2 |         1271.98 |
| 15 | Proseware Desk Lamp E0130 Blue                              |                     2 |          159.9  |
| 16 | Litware 80mm LED Dual PCI Slot Fan E1501 Blue               |                     2 |           61.98 |
| 17 | Proseware Air conditioner 12000BTU M640 Red                 |                     2 |          919.98 |
| 18 | Litware 18'' Oscillating Pedestal Fan M145 Blue             |                     2 |          800    |
| 19 | Proseware Chandelier M0615 Silver                           |                     2 |          459.98 |
| 20 | Adventure Works Chandelier M8150 White                      |                     2 |          537    |
| 21 | Contoso Home Theater System 5.1 Channel M1530 Black         |                     2 |          798    |
| 22 | WWI Chandelier M615 White                                   |                     2 |          459.98 |
| 23 | Litware Wall Lamp E3015 Silver                              |                     2 |          203.98 |
| 24 | Contoso Home Theater System 4.1 Channel M1400 White         |                     2 |          818    |
| 25 | Litware Wall Lamp E2015 Grey                                |                     2 |          239.98 |
| 26 | Litware Home Theater System 7.1 Channel M710 Brown          |                     2 |         1598    |
| 27 | Proseware Desk Lamp E0120 Blue                              |                     2 |           59.98 |
| 28 | Contoso Air conditioner 6000BTU E0180 Grey                  |                     3 |          599.97 |
| 29 | Litware Chandelier M8015 Grey                               |                     3 |          805.5  |
| 30 | Proseware Desk Lamp E0130 Grey                              |                     3 |          239.85 |
| 31 | WWI Desk Lamp E120 Silver                                   |                     3 |           89.97 |
| 32 | Litware 120mm Blue LED Case Fan E901 Black                  |                     3 |           29.97 |
| 33 | Contoso Home Theater System 2.1 Channel E1220 White         |                     3 |          597    |
| 34 | Contoso Home Theater System 5.1 Channel M1520 Black         |                     3 |         1017    |
| 35 | Proseware Air conditioner 25000BTU L167 Red                 |                     3 |         1907.97 |
| 36 | Litware Home Theater System 2.1 Channel E211 Brown          |                     3 |          809.7  |
| 37 | Litware Desk Lamp E1020 White                               |                     3 |           89.97 |
| 38 | Litware Floor Lamp X1015 Black                              |                     3 |         1907.97 |
| 39 | WWI Desk Lamp E120 Black                                    |                     3 |           89.97 |
| 40 | Contoso Home Theater System 2.1 Channel E1200 Black         |                     3 |          897    |
| 41 | Adventure Works Chandelier M6150 White                      |                     3 |          689.97 |
| 42 | Litware Chandelier M6015 White                              |                     3 |          689.97 |
| 43 | Litware Home Theater System 5.1 Channel M514 Silver         |                     3 |         1797    |
| 44 | Litware Home Theater System 2.1 Channel E212 Black          |                     3 |          899.7  |
| 45 | Proseware Chandelier M0615 Grey                             |                     3 |          689.97 |
| 46 | Proseware Floor Lamp X0115 Grey                             |                     3 |         1907.97 |
| 47 | Proseware Air conditioner 8000BTU M320 Red                  |                     3 |         1199.97 |
| 48 | Litware Wall Lamp E3015 Blue                                |                     3 |          305.97 |
| 49 | Litware 80mm LED Dual PCI Slot Fan E1501 Yellow             |                     3 |           92.97 |
| 50 | Contoso Washer & Dryer 24in M240 White                      |                     4 |         7272    |
| 51 | Litware Wall Lamp E3015 White                               |                     4 |          407.96 |
| 52 | Litware Wall Lamp E3015 Grey                                |                     4 |          407.96 |
| 53 | Litware Home Theater System 5.1 Channel M513 Brown          |                     4 |         2756    |
| 54 | Litware Home Theater System 5.1 Channel M514 Black          |                     4 |         2396    |
| 55 | Litware 180 CFM Vertical Discharge Fan X450 White           |                     4 |          862.48 |
| 56 | Adventure Works Chandelier M6150 Grey                       |                     4 |          919.96 |
| 57 | Litware Desk Lamp E1030 White                               |                     4 |          319.8  |
| 58 | Litware Home Theater System 4.1 Channel M410 Brown          |                     4 |         2396    |
| 59 | Litware 80mm Dual Ball Bearing Case Fan E1001 Green         |                     4 |           19.96 |
| 60 | Contoso SLR Camera 35" M358 Blue                            |                     4 |         1432    |
| 61 | Litware Wall Lamp E3015 Black                               |                     4 |          407.96 |
| 62 | Contoso Wireless Notebook Optical Mouse M35 Orange          |                     4 |          119.8  |
| 63 | Proseware Air conditioner 5200BTU E100 Silver               |                     4 |          439.96 |
| 64 | Adventure Works Floor Lamp M2150 White                      |                     4 |         1356    |
| 65 | Adventure Works Wall Lamp E2150 Black                       |                     4 |          479.96 |
| 66 | WWI Wall Lamp E315 Black                                    |                     4 |          407.96 |
| 67 | Litware Home Theater System 2.1 Channel E212 Silver         |                     4 |         1199.6  |
| 68 | WWI Wall Lamp E315 Grey                                     |                     4 |          407.96 |
| 69 | Contoso Smart Battery M901 Blue                             |                     5 |           57.5  |
| 70 | Litware 3-Speed Oscillating High-Performance Fan E201 Black |                     5 |          149.95 |
| 71 | WWI Desk Lamp E130 Grey                                     |                     5 |          399.75 |
| 72 | Proseware Desk Lamp E0120 Silver                            |                     5 |          149.95 |
| 73 | Contoso ADSL Modem Splitter/Filter X 3 E300 Black           |                     5 |          264.5  |
| 74 | Contoso Home Theater System 7.1 Channel M1700 Brown         |                     5 |         4445    |
| 75 | WWI Chandelier M615 Grey                                    |                     5 |         1149.95 |
| 76 | Contoso Home/Office Laptop Power Adapter E300 Grey          |                     5 |          127.5  |
| 77 | Proseware Air conditioner 8000BTU M320 Silver               |                     5 |         1999.95 |
| 78 | Litware Home Theater System 5.1 Channel M510 Black          |                     5 |         3195    |
| 79 | Proseware Desk Lamp E0130 Black                             |                     5 |          399.75 |
| 80 | WWI Wall Lamp E215 White                                    |                     5 |          599.95 |
| 81 | Litware Floor Lamp X1015 White                              |                     5 |         3179.95 |
| 82 | NT Washer & Dryer 21in E2100 Silver                         |                     5 |         7999.5  |
| 83 | Litware Home Theater System 4.1 Channel M412 Black          |                     5 |         2845    |
| 84 | Litware 17'' Oscillating Pedestal Fan M125 White            |                     5 |         1050    |
| 85 | WWI Desk Lamp E120 Blue                                     |                     5 |          149.95 |
| 86 | Contoso Home Theater System 4.1 Channel M1400 Silver        |                     5 |         2045    |
| 87 | Litware Wall Lamp E2015 Blue                                |                     6 |          719.94 |
| 88 | NT Washer & Dryer 24in M2400 White                          |                     6 |        10913.4  |
| 89 | Contoso Home Theater System 2.1 Channel E1200 Brown         |                     6 |         1794    |
| 90 | WWI Floor Lamp M215 White                                   |                     6 |         2034    |
| 91 | WWI Chandelier M815 Silver                                  |                     6 |         1611    |
| 92 | SV 4GB Laptop Memory M65 Black                              |                     6 |          474    |
| 93 | WWI Chandelier M815 Grey                                    |                     6 |         1611    |
| 94 | Contoso Lens cap E80 Grey                                   |                     6 |          179.7  |
| 95 | Proseware Wall Lamp E0215 Grey                              |                     6 |          719.94 |
| 96 | Contoso Air conditioner 12000BTU M0640 Silver               |                     6 |         2759.94 |
| 97 | WWI Desk Lamp E130 Silver                                   |                     6 |          479.7  |
| 98 | SV 4GB Laptop Memory M65 Blue                               |                     6 |          474    |
| 99 | Litware Washer & Dryer 24in M260 White                      |                     6 |        10908    |
+----+-------------------------------------------------------------+-----------------------+-----------------+

In [ ]:
7.Profitability Analysis

In [63]:


from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    Productkey,
    SUM((`Unit Price USD` -  `Unit Cost USD`) * Quantity) AS Profit
FROM 
    data_spark1
GROUP BY 
    Productkey
ORDER BY 
    Profit DESC limit 100;


""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Profitability_Analysis.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+--------------+----------+
|    |   Productkey |   Profit |
|----+--------------+----------|
|  0 |          444 | 337986   |
|  1 |          416 | 311664   |
|  2 |          428 | 310368   |
|  3 |          422 | 299353   |
|  4 |          433 | 292225   |
|  5 |          455 | 283908   |
|  6 |          450 | 282679   |
|  7 |          147 | 263727   |
|  8 |          146 | 250153   |
|  9 |          438 | 240892   |
| 10 |          145 | 236579   |
| 11 |          148 | 207491   |
| 12 |          434 | 168564   |
| 13 |          423 | 166300   |
| 14 |          417 | 155299   |
| 15 |         2100 | 154849   |
| 16 |         2095 | 144986   |
| 17 |         2085 | 139068   |
| 18 |          439 | 138289   |
| 19 |          451 | 137685   |
| 20 |         2105 | 136109   |
| 21 |          456 | 135269   |
| 22 |         2110 | 133150   |
| 23 |          164 | 133084   |
| 24 |          429 | 131232   |
| 25 |          540 | 126998   |
| 26 |          163 | 126696   |
| 27 |          427 | 120580   |
| 28 |          421 | 117540   |
| 29 |          420 | 116884   |
| 30 |          445 | 116549   |
| 31 |          539 | 108958   |
| 32 |          161 | 108596   |
| 33 |         2090 | 108493   |
| 34 |          432 | 107573   |
| 35 |          623 |  98590.8 |
| 36 |         1927 |  98429.4 |
| 37 |         1897 |  98429.4 |
| 38 |          551 |  98215.7 |
| 39 |         2106 |  98111.8 |
| 40 |          437 |  98016   |
| 41 |          426 |  96055.7 |
| 42 |          612 |  95248.7 |
| 43 |          576 |  95248.7 |
| 44 |          425 |  94052.4 |
| 45 |          600 |  93577.7 |
| 46 |          587 |  92077.2 |
| 47 |          599 |  92077.2 |
| 48 |         2086 |  91950.2 |
| 49 |          611 |  90542.6 |
| 50 |          159 |  90309.3 |
| 51 |          634 |  90235.6 |
| 52 |          419 |  89168.9 |
| 53 |          633 |  89008   |
| 54 |         1206 |  88666.9 |
| 55 |          436 |  88626.3 |
| 56 |         2096 |  88158.4 |
| 57 |          157 |  87338.6 |
| 58 |          622 |  85938.7 |
| 59 |          449 |  85395   |
| 60 |          162 |  84108.9 |
| 61 |          152 |  83991.2 |
| 62 |         2102 |  81177.5 |
| 63 |          443 |  79362.7 |
| 64 |         1443 |  79163.9 |
| 65 |          150 |  76859.9 |
| 66 |         1409 |  73650   |
| 67 |           56 |  73234.1 |
| 68 |          149 |  72898   |
| 69 |         1909 |  72752.2 |
| 70 |           53 |  72442.4 |
| 71 |          552 |  71854.3 |
| 72 |         2087 |  71778   |
| 73 |         2091 |  70621.5 |
| 74 |         1933 |  70612.4 |
| 75 |         1975 |  70612.4 |
| 76 |          158 |  70108.5 |
| 77 |         1426 |  69711.5 |
| 78 |          424 |  68938.7 |
| 79 |          402 |  68621   |
| 80 |         1951 |  68472.6 |
| 81 |          460 |  68208   |
| 82 |          431 |  68007.1 |
| 83 |         1609 |  67975.3 |
| 84 |          368 |  66883.7 |
| 85 |          435 |  66821.6 |
| 86 |          448 |  66811.5 |
| 87 |          151 |  66559.1 |
| 88 |         1915 |  66332.9 |
| 89 |          563 |  65988.7 |
| 90 |         1605 |  65929.4 |
| 91 |         2092 |  65796.5 |
| 92 |           54 |  64921   |
| 93 |         1408 |  64378.9 |
| 94 |         1650 |  64184.2 |
| 95 |         1660 |  63796.4 |
| 96 |         1655 |  63020.7 |
| 97 |          160 |  62978.8 |
| 98 |          518 |  62756.6 |
| 99 |          410 |  62540.6 |
+----+--------------+----------+

In [ ]:
8.Product Popularity by Category

In [47]:


from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    Category, 
    SUM(Quantity) AS total_quantity_sold
FROM 
    data_spark1
GROUP BY 
    Category
ORDER BY 
    total_quantity_sold DESC;



""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Product_Popularity_by_Category.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+-------------------------------+-----------------------+
|    | Category                      |   total_quantity_sold |
|----+-------------------------------+-----------------------|
|  0 | Computers                     |                 44151 |
|  1 | Cell phones                   |                 31477 |
|  2 | Music, Movies and Audio Books |                 28802 |
|  3 | Audio                         |                 23490 |
|  4 | Games and Toys                |                 22591 |
|  5 | Home Appliances               |                 18401 |
|  6 | Cameras and camcorders        |                 17609 |
|  7 | TV and Video                  |                 11236 |
+----+-------------------------------+-----------------------+

In [ ]:
Store Analysis

In [13]:




# Execute your query
my_cursor.execute("""SELECT 
    'In_Store' AS Purchase_Type,
    COUNT(*) AS Sales_Count
FROM 
    Data_Spark1
WHERE 
    `Delivery Date` = 'In_Store'

UNION ALL

SELECT 
    'Online' AS Purchase_Type,
    COUNT(*) AS Sales_Count
FROM 
    Data_Spark1
WHERE 
    `Delivery Date` = 'Online';


""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Store_Performance_Based_on_store_location.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+-----------------+---------------+
|    | Purchase_Type   |   Sales_Count |
|----+-----------------+---------------|
|  0 | In_Store        |         49719 |
|  1 | Online          |         13165 |
+----+-----------------+---------------+

In [ ]:
9.Store Performance Based on Sales and Size

In [59]:


from tabulate import tabulate
my_cursor.execute("""
   SELECT 
    Storekey, 
    SUM(Quantity * `Unit Cost usd`) AS Total_Sales, 
    `Square Meters`
FROM 
    data_spark1
GROUP BY 
    Storekey, `Square Meters`
ORDER BY 
    Total_Sales DESC;





""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Store_Performance_Based_on_Sales_Size.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+------------+------------------+-----------------+
|    |   Storekey |      Total_Sales |   Square Meters |
|----+------------+------------------+-----------------|
|  0 |          0 |      4.73163e+06 |               0 |
|  1 |         55 | 587334           |            2000 |
|  2 |         50 | 575079           |            2000 |
|  3 |         54 | 574096           |            2000 |
|  4 |          9 | 561393           |            1500 |
|  5 |         45 | 557516           |            2000 |
|  6 |         59 | 547570           |            2000 |
|  7 |         57 | 541516           |            1645 |
|  8 |         61 | 540687           |            2000 |
|  9 |         64 | 514067           |            1330 |
| 10 |         65 | 513694           |            1785 |
| 11 |         43 | 509162           |            1190 |
| 12 |          8 | 509145           |            2105 |
| 13 |         44 | 505855           |            2000 |
| 14 |         56 | 499622           |            1260 |
| 15 |         66 | 497774           |             840 |
| 16 |         53 | 497159           |            1260 |
| 17 |         47 | 475085           |            1120 |
| 18 |         51 | 470766           |            1295 |
| 19 |         10 | 436887           |            1210 |
| 20 |         48 | 436020           |            1540 |
| 21 |         38 | 415465           |            1800 |
| 22 |         30 | 395678           |            2100 |
| 23 |         49 | 389074           |            2000 |
| 24 |         40 | 378540           |            1300 |
| 25 |         29 | 375314           |            1000 |
| 26 |         39 | 372616           |            2100 |
| 27 |         42 | 370355           |            1900 |
| 28 |         36 | 350646           |            1300 |
| 29 |          5 | 349721           |            2000 |
| 30 |         37 | 348032           |            2100 |
| 31 |         63 | 335632           |            2000 |
| 32 |         24 | 278135           |            1855 |
| 33 |         62 | 274558           |            1120 |
| 34 |         22 | 270563           |            2000 |
| 35 |         27 | 268597           |            2000 |
| 36 |         23 | 255819           |            1365 |
| 37 |         19 | 237014           |            1295 |
| 38 |          6 | 222349           |            2000 |
| 39 |          4 | 176103           |            2000 |
| 40 |         34 | 173590           |            1365 |
| 41 |         33 | 170366           |            1540 |
| 42 |         21 | 167463           |             560 |
| 43 |         41 | 162616           |            2100 |
| 44 |         32 | 160381           |             910 |
| 45 |         20 | 157065           |            1715 |
| 46 |         31 | 149242           |            1085 |
| 47 |         26 | 115087           |             350 |
| 48 |          1 | 101674           |             595 |
| 49 |         18 |  91001.1         |             310 |
| 50 |         15 |  87022           |             400 |
| 51 |         16 |  79093.9         |             385 |
| 52 |         28 |  79001           |            1200 |
| 53 |         12 |  76006.5         |             350 |
| 54 |         17 |  67157.8         |             350 |
| 55 |         13 |  61967.5         |             245 |
| 56 |         14 |  42122.5         |             350 |
| 57 |          2 |   5663.38        |             665 |
+----+------------+------------------+-----------------+

In [ ]:
10.Geographical Analysis of Sales by Store Location

In [61]:


from tabulate import tabulate
my_cursor.execute("""
  SELECT 
    Storekey, Country, City, 
    SUM(Quantity * `Unit Cost usd`) AS Total_Sales
FROM 
    data_spark1
GROUP BY 
    Storekey, Country, City
ORDER BY 
    Total_Sales DESC;






""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("Geographical_Analysis_of_Sales_by _StoreLocation.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+-------+------------+----------------+--------------------------------------+---------------+
|       |   Storekey | Country        | City                                 |   Total_Sales |
|-------+------------+----------------+--------------------------------------+---------------|
|     0 |          8 | Canada         | Toronto                              |      72255.6  |
|     1 |          9 | Canada         | Toronto                              |      67787.4  |
|     2 |          0 | Canada         | Toronto                              |      61488.8  |
|     3 |         55 | United States  | Las Vegas                            |      50933.5  |
|     4 |         10 | Canada         | Toronto                              |      50519.8  |
|     5 |          0 | United States  | New York                             |      49092.9  |
|     6 |         64 | United States  | Washington                           |      44649.9  |
|     7 |          9 | Canada         | Montreal                             |      43943.4  |
|     8 |          0 | United States  | Los Angeles                          |      38776.9  |
|     9 |          0 | United States  | Portland                             |      38013.4  |
|    10 |         44 | United States  | Little Rock                          |      37360.1  |
|    11 |         55 | United States  | Reno                                 |      33659.9  |
|    12 |          9 | Canada         | Ottawa                               |      33370.2  |
|    13 |          0 | United States  | Houston                              |      31324.8  |
|    14 |          8 | Canada         | Montreal                             |      30419    |
|    15 |          9 | Canada         | Calgary                              |      30072.4  |
|    16 |         59 | United States  | Portland                             |      29035    |
|    17 |         57 | United States  | Albuquerque                          |      26944.1  |
|    18 |         59 | United States  | Eugene                               |      26690.7  |
|    19 |         61 | United States  | Columbia                             |      26525.6  |
|    20 |          8 | Canada         | Vancouver                            |      25515.6  |
|    21 |          8 | Canada         | Calgary                              |      25062.3  |
|    22 |         61 | United States  | Greenville                           |      25029.8  |
|    23 |         50 | United States  | Philadelphia                         |      24907.3  |
|    24 |          0 | Canada         | Calgary                              |      24731.4  |
|    25 |          0 | United States  | Chicago                              |      24382.8  |
|    26 |          0 | United States  | Philadelphia                         |      24032.8  |
|    27 |          0 | United States  | Dallas                               |      23881.8  |
|    28 |         45 | United States  | Hartford                             |      22701.9  |
|    29 |          0 | United States  | Southfield                           |      22341.9  |
|    30 |          0 | Canada         | Montreal                             |      21908.9  |
|    31 |         50 | United States  | Wichita                              |      21395.6  |
|    32 |          0 | United States  | Pittsburgh                           |      21174.9  |
|    33 |         54 | United States  | Lincoln                              |      20762.9  |
|    34 |          0 | Canada         | Victoria                             |      19759    |
|    35 |          0 | United States  | Jackson                              |      19673.7  |
|    36 |         54 | United States  | Omaha                                |      19526.4  |
|    37 |         63 | United States  | Salt Lake City                       |      19523    |
|    38 |          9 | Canada         | Vancouver                            |      19227.5  |
|    39 |          0 | United States  | Providence                           |      19152.7  |
|    40 |          0 | United States  | Oakland                              |      19100.7  |
|    41 |         10 | Canada         | Montreal                             |      19085    |
|    42 |         10 | Canada         | Ottawa                               |      19055.1  |
|    43 |         10 | Canada         | Vancouver                            |      18741.7  |
|    44 |          0 | United States  | Saint Louis                          |      18301.6  |
|    45 |         45 | United States  | New Haven                            |      17969.1  |
|    46 |          0 | United States  | Phoenix                              |      17936.5  |
|    47 |          0 | United States  | Indianapolis                         |      17456.5  |
|    48 |         57 | United States  | Chicago                              |      16027.8  |
|    49 |         64 | United States  | Los Angeles                          |      15928.4  |
|    50 |         64 | United States  | New York                             |      15863.9  |
|    51 |          0 | Canada         | Ottawa                               |      15745.9  |
|    52 |          9 | Canada         | Quebec                               |      15378    |
|    53 |         65 | United States  | Wheeling                             |      15065    |
|    54 |          0 | United States  | Austin                               |      15013.1  |
|    55 |          0 | United States  | Toledo                               |      14951    |
|    56 |         10 | Canada         | Edmonton                             |      14929.5  |
|    57 |         53 | United States  | Lacassine                            |      14581.6  |
|    58 |          0 | United States  | Fort Lauderdale                      |      14565.6  |
|    59 |          0 | United States  | Baltimore                            |      14496.4  |
|    60 |          0 | United States  | Montgomery                           |      14385.5  |
|    61 |          0 | United States  | Albany                               |      14330.5  |
|    62 |          0 | United States  | Memphis                              |      14171.6  |
|    63 |          0 | United States  | Charlotte                            |      14159.1  |
|    64 |         55 | United States  | Los Angeles                          |      14119.5  |
|    65 |          0 | United States  | Madison                              |      13999.4  |
|    66 |         66 | United States  | Los Angeles                          |      13899.5  |
|    67 |         45 | United States  | Bloomfield                           |      13652.2  |
|    68 |         24 | Germany        | Rantum                               |      13626.9  |
|    69 |          0 | Germany        | Lütjenwestedt                        |      13560    |
|    70 |          0 | United States  | Las Vegas                            |      13481.8  |
|    71 |          0 | United States  | Miami                                |      13452.3  |
|    72 |         61 | United States  | New York                             |      13394.8  |
|    73 |         57 | United States  | New York                             |      13364.8  |
|    74 |          0 | United States  | Richmond                             |      13241.8  |
|    75 |          0 | United States  | Tampa                                |      13191.7  |
|    76 |         61 | United States  | Florence                             |      13078.7  |
|    77 |          8 | Canada         | Edmonton                             |      13025.9  |
|    78 |         44 | United States  | Pine Bluff                           |      13003.9  |
|    79 |          8 | Canada         | Ottawa                               |      12917.8  |
|    80 |         65 | United States  | Charleston                           |      12912.9  |
|    81 |          0 | United States  | Little Rock                          |      12883.5  |
|    82 |         66 | United States  | Anaheim                              |      12872.9  |
|    83 |         53 | United States  | Houston                              |      12799    |
|    84 |          8 | Canada         | Quebec                               |      12782.1  |
|    85 |          0 | Canada         | Saskatoon                            |      12699.2  |
|    86 |         51 | United States  | Portland                             |      12615    |
|    87 |         10 | Canada         | Winnipeg                             |      12594.1  |
|    88 |         62 | United States  | Hosmer                               |      12571.8  |
|    89 |          0 | United States  | Corpus Christi                       |      12539.7  |
|    90 |         57 | United States  | Atlanta                              |      12463.7  |
|    91 |         66 | United States  | Dallas                               |      12463.3  |
|    92 |          0 | United States  | Cleveland                            |      12035.5  |
|    93 |          0 | United States  | Fresno                               |      11919.6  |
|    94 |         10 | Canada         | Quebec                               |      11916.5  |
|    95 |         55 | United States  | Philadelphia                         |      11897.3  |
|    96 |         66 | United States  | Chicago                              |      11870.1  |
|    97 |         59 | United States  | Dallas                               |      11813.7  |
|    98 |         30 | Italy          | Orgosolo                             |      11806.6  |
|    99 |         66 | United States  | Mountain View                        |      11786.1  |
|   100 |         44 | United States  | Springdale                           |      11780.6  |
|   101 |         61 | United States  | Conway                               |      11763.6  |
|   102 |          0 | United States  | Atlanta                              |      11760.8  |
|   103 |          9 | Canada         | Edmonton                             |      11759.3  |
|   104 |         44 | United States  | Fort Smith                           |      11713.3  |
|   105 |          0 | United States  | Orlando                              |      11713    |
|   106 |         49 | United States  | Dubuque                              |      11626.4  |
|   107 |         53 | United States  | Miami                                |      11624.2  |
|   108 |          0 | United States  | San Francisco                        |      11572.7  |
|   109 |         50 | United States  | Houston                              |      11512.3  |
|   110 |          8 | Canada         | Merrickville                         |      11502.6  |
|   111 |         45 | United States  | Norwalk                              |      11451.7  |
|   112 |         65 | United States  | New York                             |      11450.8  |
|   113 |          0 | United States  | Grand Rapids                         |      11329.6  |
|   114 |         57 | United States  | Los Angeles                          |      11302.2  |
|   115 |         47 | United States  | Atlanta                              |      11289    |
|   116 |         53 | United States  | Southfield                           |      11286.5  |
|   117 |         48 | United States  | Boise                                |      11273.9  |
|   118 |          8 | Canada         | Victoria                             |      11233.5  |
|   119 |         61 | United States  | Philadelphia                         |      11224    |
|   120 |         63 | United States  | New York                             |      11157.3  |
|   121 |         55 | United States  | Orlando                              |      11144.2  |
|   122 |         61 | United States  | Piedmont                             |      11061.7  |
|   123 |         47 | United States  | Honolulu                             |      11046.2  |
|   124 |         65 | United States  | Houston                              |      11015.4  |
|   125 |          0 | United States  | Woburn                               |      11009.4  |
|   126 |          0 | Netherlands    | Rotterdam                            |      10964.8  |
|   127 |         54 | United States  | Grand Island                         |      10915.6  |
|   128 |         65 | United States  | Sacramento                           |      10829.1  |
|   129 |          0 | United States  | Denver                               |      10798    |
|   130 |         56 | United States  | Manchester                           |      10692    |
|   131 |          0 | United States  | Cincinnati                           |      10672.3  |
|   132 |          0 | United States  | Florence                             |      10633.1  |
|   133 |         48 | United States  | Pottsville                           |      10628.4  |
|   134 |          0 | United States  | Jacksonville                         |      10627.3  |
|   135 |         53 | United States  | Philadelphia                         |      10607.1  |
|   136 |         47 | United States  | Wahiawa                              |      10588.1  |
|   137 |         56 | United States  | Columbus                             |      10572    |
|   138 |         66 | United States  | Cheyenne                             |      10561.4  |
|   139 |         64 | United States  | Chicago                              |      10560.6  |
|   140 |         32 | Netherlands    | Sassenheim                           |      10470.7  |
|   141 |         53 | United States  | New York                             |      10469.1  |
|   142 |         27 | Germany        | Düsseldorf Golzheim                  |      10400.2  |
|   143 |          0 | United States  | Columbus                             |      10399.3  |
|   144 |         22 | Germany        | Merzig                               |      10387.1  |
|   145 |         65 | United States  | Pensacola                            |      10380.4  |
|   146 |         50 | United States  | Brewster                             |      10374.2  |
|   147 |          0 | United States  | Norcross                             |      10300.2  |
|   148 |         49 | United States  | Los Angeles                          |      10300    |
|   149 |          9 | Canada         | Brantford                            |      10264.9  |
|   150 |          0 | Australia      | BANDYA                               |      10257.8  |
|   151 |         55 | United States  | Phoenix                              |      10223.7  |
|   152 |         64 | United States  | Columbus                             |      10186.3  |
|   153 |          0 | United States  | Minneapolis                          |      10145.7  |
|   154 |          0 | United States  | San Jose                             |      10143.1  |
|   155 |         65 | United States  | Chicago                              |      10143    |
|   156 |          5 | Australia      | SEVILLE                              |      10140.5  |
|   157 |         61 | United States  | Houston                              |      10126.9  |
|   158 |         53 | United States  | Akron                                |      10119.1  |
|   159 |         56 | United States  | Miami                                |      10039.4  |
|   160 |         54 | United States  | Plano                                |      10008.3  |
|   161 |         34 | Netherlands    | Uithoorn                             |       9989.66 |
|   162 |         43 | United States  | Los Angeles                          |       9963.33 |
|   163 |         33 | Netherlands    | Abcoude                              |       9952.23 |
|   164 |         56 | United States  | Bon Wier                             |       9927.81 |
|   165 |         48 | United States  | Los Angeles                          |       9871.66 |
|   166 |         30 | Italy          | Marmora                              |       9800.63 |
|   167 |         65 | United States  | Anaheim                              |       9758.06 |
|   168 |          0 | United States  | Lexington                            |       9740.74 |
|   169 |         24 | Germany        | Kreimbach-Kaulbach                   |       9690.97 |
|   170 |         50 | United States  | Hays                                 |       9664.17 |
|   171 |         57 | United States  | Winston Salem                        |       9663.9  |
|   172 |          5 | Australia      | METUNG                               |       9635.7  |
|   173 |         37 | United Kingdom | REDNAL                               |       9607.22 |
|   174 |          0 | Canada         | Edmonton                             |       9597.72 |
|   175 |         50 | United States  | Dallas                               |       9568.43 |
|   176 |         44 | United States  | Wawaka                               |       9559.2  |
|   177 |         34 | Netherlands    | s-Gravenpolder                       |       9541.98 |
|   178 |          0 | United States  | Midland                              |       9507.72 |
|   179 |         66 | United States  | Newark                               |       9470.47 |
|   180 |          0 | Germany        | Scharnebeck                          |       9424.81 |
|   181 |         50 | United States  | Memphis                              |       9380.69 |
|   182 |         51 | United States  | Memphis                              |       9346.38 |
|   183 |          0 | Canada         | Vancouver                            |       9317.68 |
|   184 |         61 | United States  | Chicago                              |       9299.39 |
|   185 |         55 | United States  | North Las Vegas                      |       9262.16 |
|   186 |          0 | United States  | Beaverton                            |       9251.61 |
|   187 |          0 | United States  | Boston                               |       9231.02 |
|   188 |         47 | United States  | Waimea                               |       9216.21 |
|   189 |         59 | United States  | Ada                                  |       9150.8  |
|   190 |         59 | United States  | Charlotte                            |       9145.5  |
|   191 |          8 | Canada         | Vernon                               |       9109.3  |
|   192 |         48 | United States  | Tampa                                |       9089.75 |
|   193 |         64 | United States  | Jersey City                          |       9058.04 |
|   194 |         59 | United States  | Lyerly                               |       9056.43 |
|   195 |          0 | Canada         | Shawville                            |       9046.33 |
|   196 |         45 | United States  | Southfield                           |       9005.96 |
|   197 |         49 | United States  | Des Moines                           |       8989.78 |
|   198 |         53 | United States  | Seattle                              |       8984.92 |
|   199 |          9 | Canada         | Regina                               |       8983.83 |
|   200 |          5 | Australia      | DONCASTER EAST                       |       8925.19 |
|   201 |         40 | United Kingdom | KIRKLINTON                           |       8908.04 |
|   202 |          0 | Canada         | Lachute                              |       8906.3  |
|   203 |          0 | United States  | Brook Park                           |       8904.48 |
|   204 |         61 | United States  | Myrtle Beach                         |       8887.76 |
|   205 |          0 | United States  | Louisville                           |       8860.44 |
|   206 |         54 | United States  | Merna                                |       8846.43 |

In [9]:
-- size bucket vs total_sales
SELECT
    CASE
        WHEN `square meters` < 250 THEN '<250'
        WHEN `square meters` BETWEEN 250 AND 500 THEN '250 to 500'
        WHEN `square meters` BETWEEN 501 AND 750 THEN '500 to 750'
        WHEN `square meters` BETWEEN 751 AND 1000 THEN '750 to 1000'
        WHEN `square meters` BETWEEN 1001 AND 1250 THEN '1000 to 1250'
        WHEN `square meters` BETWEEN 1251 AND 1500 THEN '1250 to 1500'
        WHEN `square meters` BETWEEN 1501 AND 1750 THEN '1500 to 1750'
        WHEN `square meters` BETWEEN 1751 AND 2000 THEN '1750 to 2000'
        WHEN `square meters` > 2000 THEN '> 2000'
    END AS size_bucket,
    ROUND(SUM(unit_price_usd * quantity),2) AS total_sales
FROM overall
GROUP BY size_bucket
ORDER BY
    CASE
        WHEN size_bucket = '<250' THEN 1
        WHEN size_bucket = '250 to 500' THEN 2
        WHEN size_bucket = '500 to 750' THEN 3
        WHEN size_bucket = '750 to 1000' THEN 4
        WHEN size_bucket = '1000 to 1250' THEN 5
        WHEN size_bucket = '1250 to 1500' THEN 6
        WHEN size_bucket = '1500 to 1750' THEN 7
        WHEN size_bucket = '1750 to 2000' THEN 8
        WHEN size_bucket = '> 2000' THEN 9
    END;

SyntaxError: invalid syntax (1122973412.py, line 1)

In [17]:


from tabulate import tabulate
my_cursor.execute("""
  SELECT
    CASE
        WHEN `square meters` < 250 THEN '<250'
        WHEN `square meters` BETWEEN 250 AND 500 THEN '250 to 500'
        WHEN `square meters` BETWEEN 501 AND 750 THEN '500 to 750'
        WHEN `square meters` BETWEEN 751 AND 1000 THEN '750 to 1000'
        WHEN `square meters` BETWEEN 1001 AND 1250 THEN '1000 to 1250'
        WHEN `square meters` BETWEEN 1251 AND 1500 THEN '1250 to 1500'
        WHEN `square meters` BETWEEN 1501 AND 1750 THEN '1500 to 1750'
        WHEN `square meters` BETWEEN 1751 AND 2000 THEN '1750 to 2000'
        WHEN `square meters` > 2000 THEN '> 2000'
    END AS size,
    ROUND(SUM(`unit price usd` * quantity),2) AS total_sales
FROM Data_Spark1
GROUP BY size
ORDER BY
    CASE
        WHEN size = '<250' THEN 1
        WHEN size = '250 to 500' THEN 2
        WHEN size = '500 to 750' THEN 3
        WHEN size = '750 to 1000' THEN 4
        WHEN size = '1000 to 1250' THEN 5
        WHEN size = '1250 to 1500' THEN 6
        WHEN size = '1500 to 1750' THEN 7
        WHEN size = '1750 to 2000' THEN 8
        WHEN size = '> 2000' THEN 9
    END;





""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("store_size_analysis.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+--------------+------------------+
|    | size         |      total_sales |
|----+--------------+------------------|
|  0 | <250         |      1.15552e+07 |
|  1 | 250 to 500   |      1.3584e+06  |
|  2 | 500 to 750   | 660480           |
|  3 | 750 to 1000  |      2.51742e+06 |
|  4 | 1000 to 1250 |      4.63473e+06 |
|  5 | 1250 to 1500 |      9.50291e+06 |
|  6 | 1500 to 1750 |      3.18933e+06 |
|  7 | 1750 to 2000 |      1.80275e+07 |
|  8 | > 2000       |      4.30951e+06 |
+----+--------------+------------------+

In [ ]:
-- store_age_bucket vs total sales    

SELECT
    CASE
        WHEN YEAR(CURDATE()) - YEAR(open_date) <= 5 THEN '<=5'
        WHEN YEAR(CURDATE()) - YEAR(open_date) BETWEEN 6 AND  10 THEN '5 to 10'
        WHEN YEAR(CURDATE()) - YEAR(open_date) BETWEEN 11 AND 15 THEN '10 to 15'
        WHEN YEAR(CURDATE()) - YEAR(open_date) BETWEEN 16 AND 20 THEN '15 to 20'
    END AS store_age_bucket,
    ROUND(SUM(unit_price_usd * quantity), 2) AS total_sales
FROM overall
GROUP BY store_age_bucket
ORDER BY store_age_bucket

-- Storekey vs Country vs Continent vs State
SELECT
  storekey,Country,Continent,State,
  ROUND(SUM((unit_price_usd)*quantity),2) AS total_revenue_USD
FROM
  overall
GROUP BY
  storekey,Country,Continent,State
order by total_revenue_USD desc

In [15]:


from tabulate import tabulate
my_cursor.execute("""
  SELECT
    CASE
        WHEN YEAR(CURDATE()) - YEAR(`open date`) <= 5 THEN '<=5'
        WHEN YEAR(CURDATE()) - YEAR(`open date`) BETWEEN 6 AND  10 THEN '5 to 10'
        WHEN YEAR(CURDATE()) - YEAR(`open date`) BETWEEN 11 AND 15 THEN '10 to 15'
        WHEN YEAR(CURDATE()) - YEAR(`open date`) BETWEEN 16 AND 20 THEN '15 to 20'
    END AS store_age,
    ROUND(SUM(`unit price usd` * quantity), 2) AS total_sales
FROM Data_Spark1
GROUP BY store_age
ORDER BY store_age




""")

# Fetch the results
out = my_cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(out, columns=[desc[0] for desc in my_cursor.description])

# Save to CSV
df.to_csv("store_age_analysis.csv", index=False)

# Display the results in tabular format
print(tabulate(df, headers="keys", tablefmt="psql"))

# Commit if necessary (only if the query modifies data)
mydb.commit()

+----+-------------+------------------+
|    | store_age   |      total_sales |
|----+-------------+------------------|
|  0 | 10 to 15    |      3.31839e+07 |
|  1 | 15 to 20    |      9.31185e+06 |
|  2 | 5 to 10     |      1.298e+07   |
|  3 | <=5         | 279775           |
+----+-------------+------------------+